# Generated by Django 3.1.4 on 2022-02-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Certified', 'Certified'), ('Used', 'Used')], default='New', max_length=10)),
                ('photo1', models.ImageField(blank=True, upload_to='place_images')),
                ('photo2', models.ImageField(blank=True, upload_to='place_images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.department')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.review')),
            ],
        ),
    ]
